name: Demo CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Display Hello World
        run: echo "Hello, World!"

      - name: Check GITHUB_TOKEN 
        run: |
          echo "GITHUB_TOKEN is set."

      - name: Check API 
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user

    permissions:
      contents: read
      metadata: read
